Update Kotlin version
An exception occurred applying plugin request [id:
'dev.flutter.flutter-gradle-plugin']
> Failed to apply plugin 'dev.flutter.flutter-gradle-plugin'.
  > Error: Your project's Kotlin version (2.2.10) is lower than
  Flutter's minimum supported version of 2.2.20. Please upgrade your
  Kotlin version.
  Alternatively, use the flag
  "--android-skip-build-dependency-validation" to bypass this check.

     Potential fix: Your project's KGP version is typically defined in
     the plugins block of the `settings.gradle` file
     (/home/runner/work/digital-growth-charts-app/digital-growth-charts-app/android/settings.gradle),
     by a plugin with the id of org.jetbrains.kotlin.android.
     If you don't see a plugins block, your project was likely created
     with an older template version, in which case it is most likely
     defined in the top-level build.gradle file
     (/home/runner/work/digital-growth-charts-app/digital-growth-charts-app/android/build.gradle)
     by the ext.kotlin_version property.